/**
 * Cross-runtime parity: the shared vectors (test-vectors/observation-set-parity.json,
 * generated by cliffy-protocols/tests/parity_vectors.rs) MUST project to
 * bit-identical values through this TypeScript port.
 *
 * The doctrine, fossilized: equal sets => bit-identical projections, in
 * every runtime. Agreement is not convergence; approximation is not parity —
 * these assertions use exact equality (toEqual on f64 bits via Object.is
 * semantics of toBe), never toBeCloseTo.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, it, expect } from 'vitest';
import { ObservationSet, type Observation } from './observation.js';
import { scalarMean, vectorMean, rotorConsensus } from './projection.js';

const here = dirname(fileURLToPath(import.meta.url));
const vectorsPath = join(here, '..', '..', '..', 'test-vectors', 'observation-set-parity.json');

interface WireObservation {
  participant_id: string;
  seq: number;
  clock: { clocks: Record<string, number> };
  payload: { Scalar?: number; Vector?: { x: number; y: number; z: number }; Rotor?: { w: number; x: number; y: number; z: number } };
  grant_ref: string | null;
}

interface ParityCase {
  name: string;
  observations: WireObservation[];
  permutations: WireObservation[][];
  expected: {
    scalar_mean: number | null;
    vector_mean: { x: number; y: number; z: number } | null;
    rotor_consensus: { w: number; x: number; y: number; z: number } | null;
  };
}

function fromWire(wire: WireObservation[]): ObservationSet {
  const set = new ObservationSet();
  for (const o of wire) {
    set.insert(o as unknown as Observation);
  }
  return set;
}

function assertExactTuple(
  got: { [k: string]: number } | null,
  expected: { [k: string]: number } | null,
  keys: string[],
  context: string,
) {
  if (expected === null) {
    expect(got, `${context}: expected null`).toBeNull();
    return;
  }
  expect(got, `${context}: expected a value`).not.toBeNull();
  for (const k of keys) {
    // Object.is distinguishes -0 from +0; toBe already uses Object.is.
    // Bit-exact: the shortest-round-trip decimal in JSON parses to the
    // identical double on both runtimes.
    expect(got![k], `${context}: ${k}`).toBe(expected[k]);
  }
}

const suite = JSON.parse(readFileSync(vectorsPath, 'utf-8')) as { cases: ParityCase[] };

describe('cross-runtime parity (Rust-generated vectors)', () => {
  for (const c of suite.cases) {
    it(`${c.name}: canonical set projects bit-identically`, () => {
      const set = fromWire(c.observations);
      assertExactTuple(scalarMean(set), c.expected.scalar_mean !== null ? { v: c.expected.scalar_mean } : null, ['v'], `${c.name}/scalar_mean`);
      // scalarMean returns number | null — unwrap through the tuple helper's
      // single-key path instead of the inline wrap above.
      assertExactTuple(vectorMean(set), c.expected.vector_mean, ['x', 'y', 'z'], `${c.name}/vector_mean`);
      assertExactTuple(rotorConsensus(set), c.expected.rotor_consensus, ['w', 'x', 'y', 'z'], `${c.name}/rotor_consensus`);
    });

    for (const [i, perm] of c.permutations.entries()) {
      it(`${c.name}: permutation ${i} projects bit-identically`, () => {
        const set = fromWire(perm);
        assertExactTuple(vectorMean(set), c.expected.vector_mean, ['x', 'y', 'z'], `${c.name}/perm${i}/vector_mean`);
        assertExactTuple(rotorConsensus(set), c.expected.rotor_consensus, ['w', 'x', 'y', 'z'], `${c.name}/perm${i}/rotor_consensus`);
        const s = scalarMean(set);
        expect(s, `${c.name}/perm${i}/scalar_mean`).toBe(c.expected.scalar_mean);
      });
    }
  }
});
