// Copyright (C) 2026 Industrial Algebra
// SPDX-License-Identifier: Apache-2.0

//! Cross-runtime parity vectors — the determinism contract crossing the
//! language boundary (Phase 2 WS0; RABBIT_HOLE_2026-09-20's open question).
//!
//! The checked-in `test-vectors/observation-set-parity.json` at the repo
//! root is generated BY THIS TEST and consumed by:
//! - this crate (drift guard: regenerated bytes must equal checked-in bytes)
//! - the wasm bindings (same vectors through the JS-facing surface)
//! - cliffy-tsukoshi's vitest (bit-exact parity of the TS port)
//!
//! Regenerate after intentional behavior changes:
//!   `CLIFFY_PARITY_WRITE=1 cargo test -p cliffy-protocols --test parity_vectors`
//!
//! f64 encoding: `serde_json`'s shortest-round-trip decimal. Both Rust and
//! JS parse it correctly-rounded, so JSON numbers reproduce the exact f64
//! bit pattern on both sides — the tests assert exact equality, which IS
//! the point (agreement is not convergence; approximation is not parity).

#![allow(clippy::float_cmp)]
// Parity tests assert exact bit equality between runtimes; tolerance-based
// comparison would defeat the entire purpose.
#![allow(clippy::expect_used)]
// Test-only serialization infallibility: serde_json::to_value on our own
// types cannot fail; the workspace panic-denial lints target production
// code paths, and the probe suites carry the same allow.

use std::collections::BTreeMap;
use std::path::PathBuf;

use cliffy_protocols::observation::{
    Observation, ObservationSet, RotorObservation, VectorObservation,
};
use cliffy_protocols::projection::{rotor_consensus, scalar_mean, vector_mean};
use serde::Serialize;
use uuid::Uuid;

const SQRT2_2: f64 = std::f64::consts::FRAC_1_SQRT_2;

#[derive(Serialize)]
struct ParityCase {
    name: &'static str,
    /// The observation set in wire format (array, canonical key order).
    observations: serde_json::Value,
    /// Merge-order permutations of the same set (wire format); every
    /// permutation MUST project to the same expected values.
    permutations: Vec<serde_json::Value>,
    expected: Expected,
}

#[derive(Serialize)]
struct Expected {
    scalar_mean: Option<f64>,
    vector_mean: Option<VectorObservation>,
    rotor_consensus: Option<RotorObservation>,
}

fn project(
    name: &'static str,
    set: &ObservationSet,
    permutations: &[ObservationSet],
) -> ParityCase {
    // The drift guard's secondary assertion: every permutation projects
    // bit-identically in Rust before we ever serialize.
    let expected = Expected {
        scalar_mean: scalar_mean(set),
        vector_mean: vector_mean(set),
        rotor_consensus: rotor_consensus(set),
    };
    for perm in permutations {
        assert_eq!(
            scalar_mean(perm),
            expected.scalar_mean,
            "{name}: permutation changed scalar_mean bits"
        );
        assert_eq!(
            vector_mean(perm),
            expected.vector_mean,
            "{name}: permutation changed vector_mean bits"
        );
        assert_eq!(
            rotor_consensus(perm),
            expected.rotor_consensus,
            "{name}: permutation changed rotor_consensus bits"
        );
    }
    ParityCase {
        name,
        observations: serde_json::to_value(set).expect("set serializes"),
        permutations: permutations
            .iter()
            .map(|p| serde_json::to_value(p).expect("set serializes"))
            .collect(),
        expected,
    }
}

fn scalar(id: Uuid, seq: u64, value: f64) -> Observation {
    Observation::new_scalar(id, seq, value)
}

fn vector(id: Uuid, seq: u64, x: f64, y: f64, z: f64) -> Observation {
    Observation::new_vector(id, seq, VectorObservation { x, y, z })
}

fn rotor(id: Uuid, seq: u64, w: f64, x: f64, y: f64, z: f64) -> Observation {
    Observation::new_rotor(id, seq, RotorObservation { w, x, y, z })
}

fn set_of(observations: &[Observation]) -> ObservationSet {
    let mut set = ObservationSet::new();
    for o in observations {
        set.insert(o.clone());
    }
    set
}

/// Same members, inserted in reverse — the canonical order must absorb it.
fn reversed(observations: &[Observation]) -> ObservationSet {
    let mut set = ObservationSet::new();
    for o in observations.iter().rev() {
        set.insert(o.clone());
    }
    set
}

/// Via merge: an empty set unions the full set twice (idempotent delivery).
fn via_merge(set: &ObservationSet) -> ObservationSet {
    let mut merged = ObservationSet::new();
    merged.merge(set);
    merged.merge(set);
    merged
}

fn cases() -> Vec<ParityCase> {
    // Deterministic participants — stable vectors across regenerations.
    let a = Uuid::from_u128(0xaaaa_0000_0000_0000_0000_0000_0000_0001);
    let b = Uuid::from_u128(0xbbbb_0000_0000_0000_0000_0000_0000_0002);
    let c = Uuid::from_u128(0xcccc_0000_0000_0000_0000_0000_0000_0003);

    let mut cases = Vec::new();

    // The annihilation oracle: 10 and 5 must mean to 7.5 — the failure the
    // old machinery shipped (merged to 0). Fossilized here forever.
    let obs = vec![scalar(a, 0, 10.0), scalar(b, 0, 5.0)];
    let set = set_of(&obs);
    cases.push(project(
        "annihilation_oracle",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // Scalars from three participants, non-trivial sum order.
    let obs = vec![
        scalar(a, 0, 0.1),
        scalar(a, 1, 0.2),
        scalar(b, 0, -3.75),
        scalar(c, 0, 1e300),
        scalar(c, 1, -1e300),
    ];
    let set = set_of(&obs);
    cases.push(project(
        "scalar_mixed_magnitudes",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // Vectors: componentwise mean.
    let obs = vec![
        vector(a, 0, 1.0, 2.0, 3.0),
        vector(b, 0, -1.0, 0.5, -3.0),
        vector(c, 0, 0.25, -0.25, 0.125),
    ];
    let set = set_of(&obs);
    cases.push(project(
        "vector_componentwise",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // Single rotor is its own consensus.
    let obs = vec![rotor(a, 0, 0.6, 0.8, 0.0, 0.0)];
    let set = set_of(&obs);
    cases.push(project("rotor_single", &set, &[reversed(&obs)]));

    // Double cover: q and −q is q observed twice.
    let obs = vec![
        rotor(a, 0, 0.6, 0.8, 0.0, 0.0),
        rotor(b, 0, -0.6, -0.8, 0.0, 0.0),
    ];
    let set = set_of(&obs);
    cases.push(project(
        "rotor_double_cover",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // Opposed ±90°z rotors average to identity (w ≈ 1).
    let obs = vec![
        rotor(a, 0, SQRT2_2, 0.0, 0.0, SQRT2_2),
        rotor(b, 0, SQRT2_2, 0.0, 0.0, -SQRT2_2),
    ];
    let set = set_of(&obs);
    cases.push(project(
        "rotor_opposed_to_identity",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // The full determinism set from the Rust oracle: four rotors, three
    // participants, out-of-order seqs.
    let obs = vec![
        rotor(a, 1, 0.5, 0.5, 0.5, 0.5),
        rotor(a, 0, 0.9, 0.1, 0.2, 0.3),
        rotor(b, 0, SQRT2_2, 0.0, 0.0, SQRT2_2),
        rotor(c, 0, 0.3, -0.4, 0.5, 0.7),
    ];
    let set = set_of(&obs);
    cases.push(project(
        "rotor_multi_participant",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // Degenerate rotor (below the 1e-12 norm floor) is skipped, never
    // fabricated: consensus comes from the survivors alone.
    let obs = vec![
        rotor(a, 0, 1e-15, 0.0, 0.0, 0.0),
        rotor(b, 0, 0.6, 0.8, 0.0, 0.0),
    ];
    let set = set_of(&obs);
    cases.push(project("rotor_degenerate_skipped", &set, &[reversed(&obs)]));

    // Mixed payloads: each projection aggregates only its kind.
    let obs = vec![
        scalar(a, 0, 5.0),
        vector(a, 1, 1.0, 2.0, 3.0),
        scalar(a, 2, 10.0),
        rotor(b, 0, 0.9, 0.1, 0.2, 0.3),
        vector(b, 1, -1.0, 0.0, 1.0),
    ];
    let set = set_of(&obs);
    cases.push(project(
        "mixed_payloads",
        &set,
        &[reversed(&obs), via_merge(&set)],
    ));

    // Empty set: everything is None — never fabricate.
    let set = ObservationSet::new();
    cases.push(project("empty", &set, &[]));

    cases
}

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("test-vectors")
        .join("observation-set-parity.json")
}

#[test]
fn parity_vectors_are_stable() {
    let generated = {
        let mut map = BTreeMap::new();
        map.insert("format", serde_json::json!("observation-set-parity/v1"));
        map.insert(
            "doctrine",
            serde_json::json!(
                "equal sets => bit-identical projections, in every runtime. \
                 Canonical iteration order: (participant UUID bytes, seq). \
                 Regenerate: CLIFFY_PARITY_WRITE=1 cargo test -p cliffy-protocols --test parity_vectors"
            ),
        );
        map.insert(
            "cases",
            serde_json::to_value(cases()).expect("cases serialize"),
        );
        serde_json::to_string_pretty(&serde_json::json!(map)).expect("vectors serialize") + "\n"
    };

    let path = vectors_path();
    if std::env::var("CLIFFY_PARITY_WRITE").is_ok() {
        std::fs::create_dir_all(path.parent().expect("parent exists")).expect("mkdir");
        std::fs::write(&path, &generated).expect("write vectors");
        eprintln!("wrote {}", path.display());
        return;
    }

    let checked_in = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "parity vectors missing at {} ({e}) — generate with \
             CLIFFY_PARITY_WRITE=1 cargo test -p cliffy-protocols --test parity_vectors",
            path.display()
        )
    });
    assert_eq!(
        generated, checked_in,
        "parity vectors drifted from the Rust implementation — regenerate intentionally with \
         CLIFFY_PARITY_WRITE=1 (and update tsukoshi expectations in the same commit)"
    );
}
